language: r
latex: false
pandoc: false
fortran: false

matrix:
  include:
    - os: linux
      env: R_CODECOV=true
    - os: osx
      brew_packages: openssl

addons:
  apt:
    packages:
    - libssl-dev
    - valgrind

r_github_packages:
  - jeroenooms/jsonlite
  - jimhester/covr

warnings_are_errors: true
#r_check_revdep: true

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
